name: Porta RH Test E2E

on: [workflow_dispatch, pull_request]

jobs:
  test:
    name: test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        if: always()
        run: |
          npm install

      - name: Install Browsers
        if: always()
        run: |
          npx playwright install

      - name: Install CTRF Json Reporter
        run: |
          npm install playwright-ctrf-json-reporter

      - name: Run E2E tests
        run: |
          npx playwright test

      - name: Publish Test Results Summary
        if: always()
        run: |
          npx github-actions-ctrf playwright-report/tests-results.json

      - name: Publish Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
