name: Porta RH Test E2E

trigger:
  - main  # ou a branch que quiser monitorar

pr:
  - main  # ativa em pull requests

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Test
    displayName: Test E2E
    jobs:
      - job: test
        displayName: Run Playwright Tests
        timeoutInMinutes: 60
        steps:
          - checkout: self

          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: npm install
            displayName: 'Install dependencies'

          - script: npx playwright install
            displayName: 'Install browsers'

          - script: npm install playwright-ctrf-json-reporter
            displayName: 'Install CTRF Json Reporter'

          - script: npx playwright test
            displayName: 'Run E2E tests'

          - script: npx github-actions-ctrf playwright-report/tests-results.json
            displayName: 'Publish Test Results Summary'
            continueOnError: true

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'playwright-report'
              ArtifactName: 'playwright-report'
              publishLocation: 'Container'
